/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface CreatePkcs12Args {
  alias?: string
  password: string
  privateKeyPem: string
  certificatePem: string
  caChainPem: Array<string>
}
export interface CreatedPkcs12 {
  base64: string
}
export declare function createPkcs12(args: CreatePkcs12Args): CreatedPkcs12
