/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export const enum EncryptAlgorithm {
  PBEWithSHA1And3KeyTripleDesCBC = 'PBEWithSHA1And3KeyTripleDesCBC',
  PBEWithSHA1And2KeyTripleDesCBC = 'PBEWithSHA1And2KeyTripleDesCBC',
  PBEWithSHA1And128BitRC2CBC = 'PBEWithSHA1And128BitRC2CBC',
  PBEWithSHA1And40BitRC2CBC = 'PBEWithSHA1And40BitRC2CBC',
  AES256CBC = 'AES256CBC'
}
export const enum MacMessageDigest {
  SHA1 = 'SHA1',
  SHA256 = 'SHA256',
  SHA384 = 'SHA384',
  SHA512 = 'SHA512'
}
export interface EncryptConfig {
  certificateAlgorithm: EncryptAlgorithm
  privateKeyAlgorithm: EncryptAlgorithm
  macAlgorithm: MacMessageDigest
}
export const OPENSSL_V1_ENCRYPT_CONFIG: EncryptConfig
export const OPENSSL_V3_ENCRYPT_CONFIG: EncryptConfig
export interface CreatePkcs12Args {
  alias?: string
  password: string
  privateKeyPem: string
  certificatePem: string
  caChainPem: Array<string>
  encryptConfig?: EncryptConfig
}
export interface CreatedPkcs12 {
  base64: string
}
export declare function createPkcs12(args: CreatePkcs12Args): CreatedPkcs12
export const enum Pkcs12Object {
  Certificate = 'Certificate',
  PrivateKey = 'PrivateKey',
  CAChain = 'CAChain'
}
export interface ExtractPkcs12Args {
  base64: string
  password: string
  object: Pkcs12Object
}
export interface ExtractedPkcs12 {
  object: Pkcs12Object
  pem: string
}
export declare function extractPkcs12(args: ExtractPkcs12Args): ExtractedPkcs12
